services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: netflow-api
    env_file:
      - ./.env.production
    environment:
      NODE_ENV: production
      APP_PROFILE: production
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - netflow_uploads:/data/uploads

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    container_name: netflow-admin
    env_file:
      - ./.env.production
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_APP_PROFILE: production
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  netflow_uploads:
